apiVersion: apps/v1
kind: Deployment
metadata:
  name: casso-backend-deployment
  namespace: casso-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casso-backend
  template:
    metadata:
      labels:
        app: casso-backend
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: casso-backend
          image: minhthu1704/casso-backend:latest
          imagePullPolicy: Always
          ports: 
          - containerPort: 8000
          envFrom:
          - configMapRef: 
              name: backend-config
          - secretRef: 
              name: backend-secret
          resources:
            requests:
              memory: "150Mi"
              cpu: "150m"
            limits:
              memory: "300Mi"
              cpu: "300m"
